services:
  flask-app:
    build: .
    image: ghcr.io/lauraschuhmacher/climate-data-analyzer:latest
    container_name: lazy-lama
    command: sh -c "python /app/app.py"
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
    restart: always
